const CART_IS_OPEN = "CART_IS_OPEN";
const SET_CARD_TO_DELETE = "SET_CARD_TO_DELETE";
const CLEAR_CART = "CLEAR_CART";
const SET_CARTS_DATA = "SET_CARTS_DATA";

export default {
  CART_IS_OPEN,
  SET_CARD_TO_DELETE,

  CLEAR_CART,
  SET_CARTS_DATA,
};
