const SET_GOODS_DATA = "SET_GOODS_DATA";
const SET_GOODS_LOADING = "SET_GOODS_LOADING";
const SET_MODAL_IS_OPEN = "SET_MODAL_IS_OPEN";
const SET_CHOSEN_CARD = "SET_CHOSEN_CARD";
const CHANGE_FAVORITE_IN_CARD = "CHANGE_FAVORITE_IN_CARD";

export default {
  SET_GOODS_DATA,
  SET_GOODS_LOADING,
  SET_MODAL_IS_OPEN,
  SET_CHOSEN_CARD,
  CHANGE_FAVORITE_IN_CARD,
};
